[context.production]
command = "npm run build"

[context.branch-deploy]
command = "npm run build && cp netlify_headers _site/_headers"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
publish = ".next"
